name: phrases_to_share
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^8.1.2
  url_launcher: ^6.1.7
  share_plus: ^12.0.0
  http: ^1.5.0
  path_provider: ^2.0.15
  lottie: ^2.4.0
  google_sign_in: ^6.1.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
